Repository opendatacube/datacube-explorer, pull requests merged in 2020-09, with the labels that each got.

#185 Pin datacube version to latest stable release
  requirements-docker.txt
Labels: bug

#190 Make product audit page header sticky
  cubedash/templates/product-audit.html
Labels: UI/UX

#191 Adds scheduled CVE scanning action
  .github/workflows/scan.yml
Labels: enhancement
